---
torii_port: 50051
internal_port: 10001

users:
  - username: abakhtin
    name: Artyom Bakhtin
    groups: ['sudo']
    home: /home/abakhtin
    ssh-key:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDphN0lYnTbsAr/a8N3C2Rxo83t6wu6b23l2T7Nw7qoP1SNRHdbyDHdfQpM6fwRdkHRyO3IQGcUtiouKF9/Vd/6ecX6/J6XaTlJr6YtmNyR50i2v7gZubJCEnCI4i8WWwyF3glFNXmIrsnw+Pvwp/6TUT6kx9PYTD+SesJkJekf4ad1OidQeNv9YZS2Ws0AtoHh2LutevDEAy/udsYpaeZ7QNXUvrdmUfftUUZStzFNFBAj9FcxzBZBsA+ss6/0GXBHxD9YrSaUIp8K1v7RQukgbBfEvrmG1Nrnw3uMAUB3DLeofE5StyT+XBMZI4I0e8RdW4Dm9KsuERj0qSQakgAJ abakhtin@horn"

  - username: tyvision
    name: Anatolyi Tykushin
    groups: ['sudo']
    home: /home/tyvision
    ssh-key:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCftnKRHaBCIY1h1eHoIMg44HEZ1Uo6NtftglJH4lKGZVtNm6TxEDXpQC0dknyfhvB8CVN9Tef5u3r4c6EIY6E/sqFkfV7wHMqM59TLbkkNoFTLDKd11QCr1nKOBXxwstvWIrXHCIP8LIzIoawY3pxiPCod8p1ozYbhTSAqZJsfsJI7ZHUXT601f6knSHZUw6YSZWa5WUvTGy3Y+7qt9beXBz0hRxNgAdAVh3dP50MXl37QCcqGLD1cEPZswnF7KWOsv2lg36n16xjuZb+9XbbQUi+YbAYr2jLyQwJ8tAH4KaItF/oRQU0NnoNyaDk8dUBsqJujopTX3FgCGn+Pz7J9cqHJ2xups0bReXUaUyX7BrRA6ti02hGzWegnWrgVcbRLhBldXykjbsdkhlp8HQ2zsyy9nFSIr58uCoXfLyR3RrAUf1WZYT3WrNT7ldKNqsEj+uJoPMZNFBlPmHXgY1HMLWO7zuKPkALePgsycSSk1657axqfVCEOUiHndayTKWBpBWFDbixMBRUqw+xjwCqPWTUYml1eJjatCIMDyUw5bBCqB5RlQMu5NV6K8YpOboM5vTaG+qZa/7KLY2LG/oN/YmugtnBGAyd5XGHtQrnk56NnYb6h8iQ8bQVnxYN6fkWaqPENPae6FVCWnT5+AMmoBXDDLhSFkIcIG+bCzjc2vw=="